export type Platform = "LeetCode" | "GeeksforGeeks" | "Codeforces" | "CodeChef";
export type Difficulty = "Easy" | "Medium" | "Hard";

export type Question = {
  id: string;
  title: string;
  platform: Platform;
  difficulty: Difficulty;
  url: string;
  topic: string;
  tags: string[];
  popularity: number;
  addedAt: string;
};

export const TOPICS = [
  "Basics",
  "Sorting",
  "Arrays",
  "Binary Search",
  "Strings",
  "Linked List",
  "Recursion",
  "Bit Manipulation",
  "Stack and Queues",
  "Sliding Window & Two Pointers",
  "Heaps",
  "Greedy Algorithms",
  "Binary Trees",
  "Binary Search Trees",
  "Graphs",
  "Dynamic Programming",
  "Tries",
];

export const PLATFORMS: Platform[] = ["LeetCode", "GeeksforGeeks", "Codeforces", "CodeChef"];

const mk = (
  id: string,
  title: string,
  platform: Platform,
  difficulty: Difficulty,
  url: string,
  topic: string,
  tags: string[],
  popularity = 70,
  daysAgo = 30,
): Question => ({
  id,
  title,
  platform,
  difficulty,
  url,
  topic,
  tags,
  popularity,
  addedAt: new Date(Date.now() - daysAgo * 86400000).toISOString(),
});

// Sourced from Striver's A2Z DSA Sheet (takeuforward.org) — all problems, organized by step/topic.
export const QUESTIONS: Question[] = [
  mk("a2", "Data Types", "GeeksforGeeks", "Easy", "https://bit.ly/3Dqmgvx", "Basics", ["Step 1.1 Things to Know in C++/Java/Python or any language"], 88, 3),
  mk("a3", "If Else statements", "GeeksforGeeks", "Easy", "https://practice.geeksforgeeks.org/problems/java-if-else-decision-making0924/0?category%5B%5D=Java&amp;category%5B%5D=Java&amp;difficulty%5B%5D=-2&amp;page=1&amp;query=category%5B%5DJavadifficulty%5B%5D-2page1category%5B%5DJava", "Basics", ["Step 1.1 Things to Know in C++/Java/Python or any language"], 87, 4),
  mk("a4", "Switch Statement", "GeeksforGeeks", "Easy", "https://practice.geeksforgeeks.org/problems/java-switch-case-statement3529/1", "Basics", ["Step 1.1 Things to Know in C++/Java/Python or any language"], 86, 5),
  mk("a6", "For loops", "GeeksforGeeks", "Easy", "https://practice.geeksforgeeks.org/problems/for-loop-primecheck-java/1", "Basics", ["Step 1.1 Things to Know in C++/Java/Python or any language"], 84, 7),
  mk("a8", "Functions (Pass by Reference and Value)", "GeeksforGeeks", "Easy", "https://bit.ly/3DqE0ac", "Basics", ["Step 1.1 Things to Know in C++/Java/Python or any language"], 82, 9),
  mk("a9", "Java Collections or C++ STL", "GeeksforGeeks", "Easy", "https://takeuforward.org/c/c-stl-tutorial-most-frequent-used-stl-containers/", "Basics", ["Step 1.3 Learn STL/Java-Collections or similar thing in your languag"], 81, 10),
  mk("a10", "Count Digits", "GeeksforGeeks", "Easy", "https://practice.geeksforgeeks.org/problems/count-digits5716/1", "Basics", ["Step 1.4 Know Basic Maths"], 80, 11),
  mk("a11", "Reverse a Number", "LeetCode", "Easy", "https://leetcode.com/problems/reverse-integer/", "Basics", ["Step 1.4 Know Basic Maths"], 84, 12),
  mk("a12", "Check Palindrome", "LeetCode", "Easy", "https://leetcode.com/problems/palindrome-number/", "Basics", ["Step 1.4 Know Basic Maths"], 83, 13),
  mk("a13", "GCD Or HCF", "GeeksforGeeks", "Easy", "https://practice.geeksforgeeks.org/problems/lcm-and-gcd4516/1", "Basics", ["Step 1.4 Know Basic Maths"], 77, 14),
  mk("a14", "Armstrong Numbers", "LeetCode", "Easy", "https://leetcode.com/problems/armstrong-number/", "Basics", ["Step 1.4 Know Basic Maths"], 81, 15),
  mk("a15", "Print all Divisors", "GeeksforGeeks", "Easy", "https://practice.geeksforgeeks.org/problems/sum-of-all-divisors-from-1-to-n4738/1", "Basics", ["Step 1.4 Know Basic Maths"], 75, 16),
  mk("a16", "Check for Prime", "GeeksforGeeks", "Easy", "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps-1587115620/1", "Basics", ["Step 1.4 Know Basic Maths"], 74, 17),
  mk("a17", "Understand recursion by print something N times", "GeeksforGeeks", "Easy", "https://bit.ly/3K2epHv", "Basics", ["Step 1.5 Learn Basic Recursion"], 73, 18),
  mk("a18", "Print name N times using recursion", "GeeksforGeeks", "Easy", "https://bit.ly/3y2BiWz", "Basics", ["Step 1.5 Learn Basic Recursion"], 72, 19),
  mk("a19", "Print 1 to N using recursion", "GeeksforGeeks", "Easy", "https://bit.ly/3w3qhDh", "Basics", ["Step 1.5 Learn Basic Recursion"], 71, 20),
  mk("a20", "Print N to 1 using recursion", "GeeksforGeeks", "Easy", "https://bit.ly/3LOkcBn", "Basics", ["Step 1.5 Learn Basic Recursion"], 70, 21),
  mk("a21", "Sum of first N numbers", "GeeksforGeeks", "Easy", "https://bit.ly/3C9KZ8G", "Basics", ["Step 1.5 Learn Basic Recursion"], 69, 22),
  mk("a22", "Factorial of N numbers", "GeeksforGeeks", "Easy", "https://bit.ly/3QugUVo", "Basics", ["Step 1.5 Learn Basic Recursion"], 68, 23),
  mk("a23", "Reverse an array", "GeeksforGeeks", "Easy", "https://bit.ly/3SRqzXU", "Basics", ["Step 1.5 Learn Basic Recursion"], 67, 24),
  mk("a24", "Check if a string is palindrome or not", "LeetCode", "Easy", "https://leetcode.com/problems/valid-palindrome/", "Basics", ["Step 1.5 Learn Basic Recursion"], 71, 25),
  mk("a25", "Fibonacci Number", "LeetCode", "Easy", "https://leetcode.com/problems/fibonacci-number/", "Basics", ["Step 1.5 Learn Basic Recursion"], 70, 26),
  mk("a26", "Counting frequencies of array elements", "GeeksforGeeks", "Easy", "https://practice.geeksforgeeks.org/problems/frequency-of-array-elements-1587115620/0", "Basics", ["Step 1.6 Learn Basic Hashing"], 64, 27),
  mk("a27", "Find the highest/lowest frequency element", "GeeksforGeeks", "Easy", "https://practice.geeksforgeeks.org/problems/top-k-frequent-elements-in-array/1", "Basics", ["Step 1.6 Learn Basic Hashing"], 63, 28),
  mk("a28", "Selection Sort", "GeeksforGeeks", "Easy", "https://bit.ly/3ppA6YJ", "Sorting", ["Step 2.1 Sorting-I"], 62, 29),
  mk("a29", "Bubble Sort", "GeeksforGeeks", "Easy", "https://bit.ly/3w6yQx8", "Sorting", ["Step 2.1 Sorting-I"], 61, 30),
  mk("a30", "Insertion Sort", "GeeksforGeeks", "Easy", "https://bit.ly/3JVcqot", "Sorting", ["Step 2.1 Sorting-I"], 90, 31),
  mk("a31", "Merge Sort", "GeeksforGeeks", "Easy", "https://bit.ly/3A30Anw", "Sorting", ["Step 2.2 Sorting-II"], 89, 32),
  mk("a32", "Recursive Bubble Sort", "GeeksforGeeks", "Easy", "https://bit.ly/3QV65vI", "Sorting", ["Step 2.2 Sorting-II"], 88, 33),
  mk("a33", "Recursive Insertion Sort", "GeeksforGeeks", "Easy", "https://bit.ly/3PxAWx1", "Sorting", ["Step 2.2 Sorting-II"], 87, 34),
  mk("a34", "Quick Sort", "GeeksforGeeks", "Easy", "https://bit.ly/3dsEbIK", "Sorting", ["Step 2.2 Sorting-II"], 86, 35),
  mk("a35", "Largest Element in an Array", "GeeksforGeeks", "Easy", "https://bit.ly/3Pld280", "Arrays", ["Step 3.1 Easy"], 85, 36),
  mk("a36", "Second Largest Element in an Array without sorting", "GeeksforGeeks", "Easy", "https://bit.ly/3pFvBcN", "Arrays", ["Step 3.1 Easy"], 84, 37),
  mk("a37", "Check if the array is sorted", "LeetCode", "Easy", "https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/#:~:text=Input%3A%20nums%20%3D%20%5B2%2C,no%20rotation)%20to%20make%20nums.", "Arrays", ["Step 3.1 Easy"], 88, 38),
  mk("a38", "Remove duplicates from Sorted array", "LeetCode", "Easy", "https://leetcode.com/problems/remove-duplicates-from-sorted-array/#:~:text=Input%3A%20nums%20%3D%20%5B0%2C,%2C%203%2C%20and%204%20respectively.", "Arrays", ["Step 3.1 Easy"], 87, 39),
  mk("a39", "Left Rotate an array by one place", "LeetCode", "Easy", "https://leetcode.com/problems/rotate-array/", "Arrays", ["Step 3.1 Easy"], 86, 40),
  mk("a40", "Left rotate an array by D places", "LeetCode", "Easy", "https://leetcode.com/problems/rotate-array/", "Arrays", ["Step 3.1 Easy"], 85, 41),
  mk("a41", "Move Zeros to end", "LeetCode", "Easy", "https://leetcode.com/problems/move-zeroes/", "Arrays", ["Step 3.1 Easy"], 84, 42),
  mk("a42", "Linear Search", "GeeksforGeeks", "Easy", "https://bit.ly/3KcpHcB", "Arrays", ["Step 3.1 Easy"], 78, 43),
  mk("a43", "Find the Union and intersection of two sorted arrays", "GeeksforGeeks", "Easy", "https://bit.ly/3Ap7Onp", "Arrays", ["Step 3.1 Easy"], 77, 44),
  mk("a44", "Find missing number in an array", "LeetCode", "Easy", "https://leetcode.com/problems/missing-number/", "Arrays", ["Step 3.1 Easy"], 81, 45),
  mk("a45", "Maximum Consecutive Ones", "LeetCode", "Easy", "https://leetcode.com/problems/max-consecutive-ones/", "Arrays", ["Step 3.1 Easy"], 80, 46),
  mk("a46", "Longest subarray with given sum(Positives)", "GeeksforGeeks", "Easy", "https://takeuforward.org/data-structure/longest-subarray-with-given-sum-k/", "Arrays", ["Step 3.1 Easy"], 74, 47),
  mk("a47", "Longest subarray with given sum(Positives + Negatives)", "GeeksforGeeks", "Easy", "https://bit.ly/3dyZdp3", "Arrays", ["Step 3.1 Easy"], 73, 48),
  mk("a48", "Find the number that appears once, and other numbers twice.", "LeetCode", "Easy", "https://leetcode.com/problems/single-number/", "Arrays", ["Step 3.1 Easy"], 77, 49),
  mk("a49", "Find number of subarrays with sum K", "LeetCode", "Medium", "https://leetcode.com/problems/subarray-sum-equals-k/", "Arrays", ["Step 3.2 Medium"], 76, 50),
  mk("a50", "Find the row with maximum number of 1’s", "GeeksforGeeks", "Medium", "https://bit.ly/3QNDw2W", "Binary Search", ["Step 4.2 Applying BS on 2D Arrays"], 70, 51),
  mk("a51", "2Sum Problem", "LeetCode", "Medium", "https://leetcode.com/problems/two-sum/", "Arrays", ["Step 3.2 Medium"], 74, 52),
  mk("a52", "Sort an array of 0’s 1’s and 2’s", "LeetCode", "Medium", "https://leetcode.com/problems/sort-colors/", "Arrays", ["Step 3.2 Medium"], 73, 53),
  mk("a53", "Majority Element (>n/2 times)", "LeetCode", "Medium", "https://leetcode.com/problems/majority-element/", "Arrays", ["Step 3.2 Medium"], 72, 54),
  mk("a54", "Kadane’s Algorithm, maximum subarray sum", "LeetCode", "Medium", "https://leetcode.com/problems/maximum-subarray/", "Arrays", ["Step 3.2 Medium"], 71, 55),
  mk("a55", "Print the subarray with maximum sum", "GeeksforGeeks", "Medium", "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/", "Arrays", ["Step 3.2 Medium"], 65, 56),
  mk("a56", "Stock Buy and Sell", "LeetCode", "Medium", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "Arrays", ["Step 3.2 Medium"], 69, 57),
  mk("a57", "Rearrange the array in alternating positive and negative items", "LeetCode", "Medium", "https://leetcode.com/problems/rearrange-array-elements-by-sign/", "Arrays", ["Step 3.2 Medium"], 68, 58),
  mk("a58", "Next Permutation", "LeetCode", "Medium", "https://leetcode.com/problems/next-permutation/", "Arrays", ["Step 3.2 Medium"], 67, 59),
  mk("a59", "Leaders in an Array problem", "GeeksforGeeks", "Medium", "https://bit.ly/3bZqbGc", "Arrays", ["Step 3.2 Medium"], 61, 60),
  mk("a60", "Longest Consecutive Sequence in an Array", "LeetCode", "Medium", "https://leetcode.com/problems/longest-consecutive-sequence/solution/", "Arrays", ["Step 3.2 Medium"], 95, 1),
  mk("a61", "Set Matrix Zeros", "LeetCode", "Medium", "https://leetcode.com/problems/set-matrix-zeroes/", "Arrays", ["Step 3.2 Medium"], 94, 2),
  mk("a62", "Rotate Matrix by 90 degrees", "LeetCode", "Medium", "https://leetcode.com/problems/rotate-image/", "Arrays", ["Step 3.2 Medium"], 93, 3),
  mk("a63", "Print the matrix in spiral manner", "LeetCode", "Medium", "https://leetcode.com/problems/spiral-matrix/", "Arrays", ["Step 3.2 Medium"], 92, 4),
  mk("a64", "Pascal’s Triangle", "LeetCode", "Hard", "https://leetcode.com/problems/pascals-triangle/", "Arrays", ["Step 3.3 Hard"], 91, 5),
  mk("a65", "Majority Element (n/3 times)", "LeetCode", "Hard", "https://leetcode.com/problems/majority-element-ii/", "Arrays", ["Step 3.3 Hard"], 90, 6),
  mk("a66", "3-Sum Problem", "LeetCode", "Hard", "https://leetcode.com/problems/3sum/", "Arrays", ["Step 3.3 Hard"], 89, 7),
  mk("a67", "4-Sum Problem", "LeetCode", "Hard", "https://leetcode.com/problems/4sum/", "Arrays", ["Step 3.3 Hard"], 88, 8),
  mk("a68", "Patterns", "GeeksforGeeks", "Easy", "https://takeuforward.org/strivers-a2z-dsa-course/must-do-pattern-problems-before-starting-dsa/", "Basics", ["Step 1.2 Build-up Logical Thinking"], 82, 9),
  mk("a69", "Count number of subarrays with given xor K", "GeeksforGeeks", "Hard", "https://bit.ly/3PrvhZs", "Arrays", ["Step 3.3 Hard"], 81, 10),
  mk("a70", "Merge Overlapping Subintervals", "LeetCode", "Hard", "https://leetcode.com/problems/merge-intervals/", "Arrays", ["Step 3.3 Hard"], 85, 11),
  mk("a71", "Merge two sorted arrays without extra space", "LeetCode", "Hard", "https://leetcode.com/problems/merge-sorted-array/", "Arrays", ["Step 3.3 Hard"], 84, 12),
  mk("a72", "Find the repeating and missing number", "GeeksforGeeks", "Hard", "https://bit.ly/3zWZoCs", "Arrays", ["Step 3.3 Hard"], 78, 13),
  mk("a73", "Count Inversions", "GeeksforGeeks", "Hard", "https://bit.ly/3PtLWLM", "Arrays", ["Step 3.3 Hard"], 77, 14),
  mk("a74", "Reverse Pairs", "LeetCode", "Hard", "https://leetcode.com/problems/reverse-pairs/", "Arrays", ["Step 3.3 Hard"], 81, 15),
  mk("a75", "Maximum Product Subarray", "LeetCode", "Hard", "https://leetcode.com/problems/maximum-product-subarray/", "Arrays", ["Step 3.3 Hard"], 80, 16),
  mk("a76", "Binary Search to find X in sorted array", "LeetCode", "Medium", "https://leetcode.com/problems/binary-search/", "Binary Search", ["Step 4.1 Learning BS on 1D Arrays"], 79, 17),
  mk("a77", "Implement Lower Bound", "GeeksforGeeks", "Medium", "https://bit.ly/3Cf398N", "Binary Search", ["Step 4.1 Learning BS on 1D Arrays"], 73, 18),
  mk("a78", "Implement Upper Bound", "GeeksforGeeks", "Medium", "https://bit.ly/3CgDDjE", "Binary Search", ["Step 4.1 Learning BS on 1D Arrays"], 72, 19),
  mk("a79", "Search Insert Position", "LeetCode", "Medium", "https://leetcode.com/problems/search-insert-position/#:~:text=Search%20Insert%20Position%20%2D%20LeetCode&amp;text=Given%20a%20sorted%20array%20of,(log%20n)%20runtime%20complexity.", "Binary Search", ["Step 4.1 Learning BS on 1D Arrays"], 76, 20),
  mk("a81", "Find the first or last occurrence of a given number in a sorted array", "LeetCode", "Medium", "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/", "Binary Search", ["Step 4.1 Learning BS on 1D Arrays"], 74, 22),
  mk("a82", "Count occurrences of a number in a sorted array with duplicates", "GeeksforGeeks", "Medium", "https://bit.ly/3SVcOqW", "Binary Search", ["Step 4.1 Learning BS on 1D Arrays"], 68, 23),
  mk("a83", "Find peak element", "LeetCode", "Medium", "https://leetcode.com/problems/find-peak-element/#:~:text=Find%20Peak%20Element%20%2D%20LeetCode&amp;text=A%20peak%20element%20is%20an,to%20any%20of%20the%20peaks.", "Binary Search", ["Step 4.1 Learning BS on 1D Arrays"], 72, 24),
  mk("a84", "Search in Rotated Sorted Array I", "LeetCode", "Medium", "https://leetcode.com/problems/search-in-rotated-sorted-array/", "Binary Search", ["Step 4.1 Learning BS on 1D Arrays"], 71, 25),
  mk("a85", "Search in Rotated Sorted Array II", "LeetCode", "Medium", "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/", "Binary Search", ["Step 4.1 Learning BS on 1D Arrays"], 70, 26),
  mk("a86", "Find minimum in Rotated Sorted Array", "LeetCode", "Medium", "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", "Binary Search", ["Step 4.1 Learning BS on 1D Arrays"], 69, 27),
  mk("a87", "Single element in a Sorted Array", "LeetCode", "Medium", "https://leetcode.com/problems/single-element-in-a-sorted-array/", "Binary Search", ["Step 4.1 Learning BS on 1D Arrays"], 68, 28),
  mk("a89", "Find out how many times has an array been rotated", "GeeksforGeeks", "Medium", "https://bit.ly/3dEvWJD", "Binary Search", ["Step 4.1 Learning BS on 1D Arrays"], 61, 30),
  mk("a90", "Search in a 2 D matrix", "LeetCode", "Medium", "https://leetcode.com/problems/search-a-2d-matrix/", "Binary Search", ["Step 4.2 Applying BS on 2D Arrays"], 95, 31),
  mk("a91", "Find Peak Element", "LeetCode", "Medium", "https://leetcode.com/problems/find-a-peak-element-ii/", "Binary Search", ["Step 4.2 Applying BS on 2D Arrays"], 94, 32),
  mk("a92", "Matrix Median", "GeeksforGeeks", "Medium", "https://bit.ly/3PvwuPk", "Binary Search", ["Step 4.2 Applying BS on 2D Arrays"], 88, 33),
  mk("a93", "Find square root of a number in log n", "GeeksforGeeks", "Medium", "https://bit.ly/3JXtGcE", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 87, 34),
  mk("a94", "Find the Nth root of a number using binary search", "GeeksforGeeks", "Medium", "https://bit.ly/3zWNyrL", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 86, 35),
  mk("a95", "Koko Eating Bananas", "LeetCode", "Medium", "https://leetcode.com/problems/koko-eating-bananas/", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 90, 36),
  mk("a96", "Minimum days to make M bouquets", "LeetCode", "Medium", "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 89, 37),
  mk("a97", "Find the smallest Divisor", "LeetCode", "Medium", "https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 88, 38),
  mk("a98", "Capacity to Ship Packages within D Days", "LeetCode", "Medium", "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 87, 39),
  mk("a99", "Median of two sorted arrays", "LeetCode", "Medium", "https://leetcode.com/problems/median-of-two-sorted-arrays/", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 86, 40),
  mk("a100", "Aggressive Cows", "GeeksforGeeks", "Medium", "https://bit.ly/3rBuE5Z", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 80, 41),
  mk("a101", "Book Allocation Problem", "GeeksforGeeks", "Medium", "https://bit.ly/3QMrMxP", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 79, 42),
  mk("a102", "Split array – Largest Sum", "LeetCode", "Medium", "https://leetcode.com/problems/split-array-largest-sum/", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 83, 43),
  mk("a103", "Kth Missing Positive Number", "LeetCode", "Medium", "https://leetcode.com/problems/kth-missing-positive-number/#:~:text=Given%20an%20array%20arr%20of,13%2C...%5D.", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 82, 44),
  mk("a104", "Minimize Max Distance to Gas Station", "LeetCode", "Medium", "https://leetcode.com/problems/minimize-max-distance-to-gas-station/", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 81, 45),
  mk("a105", "Median of 2 sorted arrays", "LeetCode", "Medium", "https://leetcode.com/problems/median-of-two-sorted-arrays/", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 80, 46),
  mk("a106", "Kth element of 2 sorted arrays", "GeeksforGeeks", "Medium", "https://bit.ly/3Amcomr", "Binary Search", ["Step 4.3 Find Answers by BS in Search Space"], 74, 47),
  mk("a107", "Remove outermost Paranthesis", "LeetCode", "Easy", "https://leetcode.com/problems/remove-outermost-parentheses/", "Strings", ["Step 5.1 Basic and Easy String Problems"], 78, 48),
  mk("a108", "Reverse words in a given string / Palindrome Check", "LeetCode", "Easy", "https://leetcode.com/problems/reverse-words-in-a-string/", "Strings", ["Step 5.1 Basic and Easy String Problems"], 77, 49),
  mk("a109", "Largest odd number in a string", "LeetCode", "Easy", "https://leetcode.com/problems/largest-odd-number-in-string/", "Strings", ["Step 5.1 Basic and Easy String Problems"], 76, 50),
  mk("a110", "Longest Common Prefix", "LeetCode", "Easy", "https://leetcode.com/problems/longest-common-prefix/", "Strings", ["Step 5.1 Basic and Easy String Problems"], 75, 51),
  mk("a111", "Isomorphic String", "LeetCode", "Easy", "https://leetcode.com/problems/isomorphic-strings/", "Strings", ["Step 5.1 Basic and Easy String Problems"], 74, 52),
  mk("a112", "check whether one string is a rotation of another", "LeetCode", "Easy", "https://leetcode.com/problems/rotate-string/", "Strings", ["Step 5.1 Basic and Easy String Problems"], 73, 53),
  mk("a113", "Check if two strings are anagram of each other", "LeetCode", "Easy", "https://leetcode.com/problems/valid-anagram/#:~:text=Given%20two%20strings%20s%20and,the%20original%20letters%20exactly%20once.&amp;text=Constraints%3A,.length%20%3C%3D%205%20*%2010", "Strings", ["Step 5.1 Basic and Easy String Problems"], 72, 54),
  mk("a114", "Sort Characters by frequency", "LeetCode", "Medium", "https://leetcode.com/problems/sort-characters-by-frequency/", "Strings", ["Step 5.2 Medium String Problems"], 71, 55),
  mk("a115", "Maximum Nesting Depth of Paranthesis", "LeetCode", "Medium", "https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/", "Strings", ["Step 5.2 Medium String Problems"], 70, 56),
  mk("a116", "Roman Number to Integer and vice versa", "LeetCode", "Medium", "https://leetcode.com/problems/roman-to-integer/", "Strings", ["Step 5.2 Medium String Problems"], 69, 57),
  mk("a117", "Implement Atoi", "LeetCode", "Medium", "https://leetcode.com/problems/string-to-integer-atoi/", "Strings", ["Step 5.2 Medium String Problems"], 68, 58),
  mk("a118", "Count Number of Substrings", "GeeksforGeeks", "Medium", "https://bit.ly/3CfQfYi", "Strings", ["Step 5.2 Medium String Problems"], 62, 59),
  mk("a119", "Longest Palindromic Substring[Do it without DP]", "LeetCode", "Medium", "https://leetcode.com/problems/longest-palindromic-substring/", "Strings", ["Step 5.2 Medium String Problems"], 66, 60),
  mk("a120", "Sum of Beauty of all substring", "LeetCode", "Medium", "https://leetcode.com/problems/sum-of-beauty-of-all-substrings/", "Strings", ["Step 5.2 Medium String Problems"], 95, 1),
  mk("a121", "Reverse Every Word in A String", "LeetCode", "Medium", "https://leetcode.com/problems/reverse-words-in-a-string/", "Strings", ["Step 5.2 Medium String Problems"], 94, 2),
  mk("a122", "Introduction toLinkedList, learn about struct, and how is node represented", "GeeksforGeeks", "Medium", "https://bit.ly/3URZnst", "Linked List", ["Step 6.1 Learn 1DLinkedList"], 88, 3),
  mk("a123", "Inserting a node inLinkedList", "GeeksforGeeks", "Medium", "https://bit.ly/3w9pEIt", "Linked List", ["Step 6.1 Learn 1DLinkedList"], 87, 4),
  mk("a124", "Deleting a node inLinkedList", "LeetCode", "Medium", "https://leetcode.com/problems/delete-node-in-a-linked-list/", "Linked List", ["Step 6.1 Learn 1DLinkedList"], 91, 5),
  mk("a125", "Find the length of theLinkedlist [learn traversal]", "GeeksforGeeks", "Medium", "https://bit.ly/3Po7tpf", "Linked List", ["Step 6.1 Learn 1DLinkedList"], 85, 6),
  mk("a126", "Search an element in the LL", "GeeksforGeeks", "Medium", "https://bit.ly/3Epriup", "Linked List", ["Step 6.1 Learn 1DLinkedList"], 84, 7),
  mk("a127", "Introduction to DLL, learn about struct, and how is node represented", "GeeksforGeeks", "Medium", "https://bit.ly/3V9wY1v", "Linked List", ["Step 6.2 Learn DoublyLinkedList"], 83, 8),
  mk("a128", "Insert a node in DLL", "GeeksforGeeks", "Medium", "https://bit.ly/3QD4hHs", "Linked List", ["Step 6.2 Learn DoublyLinkedList"], 82, 9),
  mk("a129", "Delete a node in DLL", "GeeksforGeeks", "Medium", "https://bit.ly/3QlEoMx", "Linked List", ["Step 6.2 Learn DoublyLinkedList"], 81, 10),
  mk("a130", "Reverse a DLL", "GeeksforGeeks", "Medium", "https://bit.ly/3w6hUaa", "Linked List", ["Step 6.2 Learn DoublyLinkedList"], 80, 11),
  mk("a131", "Middle of aLinkedList [TortoiseHare Method]", "LeetCode", "Medium", "https://leetcode.com/problems/middle-of-the-linked-list/", "Linked List", ["Step 6.3 Medium Problems of LL"], 84, 12),
  mk("a132", "Reverse aLinkedList [Iterative]", "LeetCode", "Medium", "https://leetcode.com/problems/reverse-linked-list/", "Linked List", ["Step 6.3 Medium Problems of LL"], 83, 13),
  mk("a133", "Reverse a LL [Recursive]", "LeetCode", "Medium", "https://leetcode.com/problems/reverse-linked-list/", "Linked List", ["Step 6.3 Medium Problems of LL"], 82, 14),
  mk("a134", "Detect a loop in LL", "LeetCode", "Medium", "https://leetcode.com/problems/linked-list-cycle/", "Linked List", ["Step 6.3 Medium Problems of LL"], 81, 15),
  mk("a135", "Find the starting point in LL", "LeetCode", "Medium", "https://leetcode.com/problems/linked-list-cycle-ii/", "Linked List", ["Step 6.3 Medium Problems of LL"], 80, 16),
  mk("a136", "Length of Loop in LL", "GeeksforGeeks", "Medium", "https://bit.ly/3dyXL6m", "Linked List", ["Step 6.3 Medium Problems of LL"], 74, 17),
  mk("a137", "Check if LL is palindrome or not", "LeetCode", "Medium", "https://leetcode.com/problems/palindrome-linked-list/", "Linked List", ["Step 6.3 Medium Problems of LL"], 78, 18),
  mk("a138", "Segrregate odd and even nodes in LL", "LeetCode", "Medium", "https://leetcode.com/problems/odd-even-linked-list/", "Linked List", ["Step 6.3 Medium Problems of LL"], 77, 19),
  mk("a139", "Remove Nth node from the back of the LL", "LeetCode", "Medium", "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", "Linked List", ["Step 6.3 Medium Problems of LL"], 76, 20),
  mk("a140", "Delete the middle node of LL", "LeetCode", "Medium", "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/#:~:text=You%20are%20given%20the%20head,than%20or%20equal%20to%20x%20.", "Linked List", ["Step 6.3 Medium Problems of LL"], 75, 21),
  mk("a141", "Sort LL", "LeetCode", "Medium", "https://leetcode.com/problems/sort-list/", "Linked List", ["Step 6.3 Medium Problems of LL"], 74, 22),
  mk("a142", "Sort a LL of 0’s 1’s and 2’s by changingLinks", "GeeksforGeeks", "Medium", "https://bit.ly/3Ceotvr", "Linked List", ["Step 6.3 Medium Problems of LL"], 68, 23),
  mk("a143", "Find the intersection point of Y LL", "LeetCode", "Medium", "https://leetcode.com/problems/intersection-of-two-linked-lists/", "Linked List", ["Step 6.3 Medium Problems of LL"], 72, 24),
  mk("a144", "Add 1 to a number represented by LL", "GeeksforGeeks", "Medium", "https://bit.ly/3piCTD3", "Linked List", ["Step 6.3 Medium Problems of LL"], 66, 25),
  mk("a145", "Add 2 numbers in LL", "LeetCode", "Medium", "https://leetcode.com/problems/add-two-numbers/", "Linked List", ["Step 6.3 Medium Problems of LL"], 70, 26),
  mk("a146", "Delete all occurrences of a key in DLL", "GeeksforGeeks", "Medium", "https://bit.ly/3zuBr66", "Linked List", ["Step 6.4 Medium Problems of DLL"], 64, 27),
  mk("a147", "Find pairs with given sum in DLL", "GeeksforGeeks", "Medium", "https://bit.ly/3zWPiBj", "Linked List", ["Step 6.4 Medium Problems of DLL"], 63, 28),
  mk("a148", "Remove duplicates from sorted DLL", "GeeksforGeeks", "Medium", "https://bit.ly/3FtJUtZ", "Linked List", ["Step 6.4 Medium Problems of DLL"], 62, 29),
  mk("a149", "Reverse LL in group of given size K", "LeetCode", "Hard", "https://leetcode.com/problems/reverse-nodes-in-k-group/", "Linked List", ["Step 6.5 Hard Problems of LL"], 66, 30),
  mk("a150", "Rotate a LL", "LeetCode", "Hard", "https://leetcode.com/problems/rotate-list/description/", "Linked List", ["Step 6.5 Hard Problems of LL"], 95, 31),
  mk("a151", "Flattening of LL", "GeeksforGeeks", "Hard", "https://bit.ly/3w9TKf8", "Linked List", ["Step 6.5 Hard Problems of LL"], 89, 32),
  mk("a152", "Clone aLinked List with random and next pointer", "LeetCode", "Hard", "https://leetcode.com/problems/copy-list-with-random-pointer/", "Linked List", ["Step 6.5 Hard Problems of LL"], 93, 33),
  mk("a153", "Recursive Implementation of atoi()", "LeetCode", "Medium", "https://leetcode.com/problems/string-to-integer-atoi/", "Recursion", ["Step 7.1 Get a Strong Hold"], 92, 34),
  mk("a154", "Pow(x, n)", "LeetCode", "Medium", "https://leetcode.com/problems/powx-n/", "Recursion", ["Step 7.1 Get a Strong Hold"], 91, 35),
  mk("a155", "Count Good numbers", "LeetCode", "Medium", "https://leetcode.com/problems/count-good-numbers/", "Recursion", ["Step 7.1 Get a Strong Hold"], 90, 36),
  mk("a156", "Sort a stack using recursion", "GeeksforGeeks", "Medium", "https://bit.ly/3Pu0YBn", "Recursion", ["Step 7.1 Get a Strong Hold"], 84, 37),
  mk("a157", "Reverse a stack using recursion", "GeeksforGeeks", "Medium", "https://bit.ly/3podAiY", "Recursion", ["Step 7.1 Get a Strong Hold"], 83, 38),
  mk("a158", "Generate all binary strings", "GeeksforGeeks", "Medium", "https://bit.ly/3sI8I9W", "Recursion", ["Step 7.2 Subsequences Pattern"], 82, 39),
  mk("a159", "Generate Paranthesis", "LeetCode", "Medium", "https://leetcode.com/problems/generate-parentheses/", "Recursion", ["Step 7.2 Subsequences Pattern"], 86, 40),
  mk("a160", "Print all subsequences/Power Set", "LeetCode", "Medium", "https://leetcode.com/problems/subsets/", "Recursion", ["Step 7.2 Subsequences Pattern"], 85, 41),
  mk("a161", "Learn All Patterns of Subsequences (Theory)", "GeeksforGeeks", "Medium", "https://bit.ly/3US225G", "Recursion", ["Step 7.2 Subsequences Pattern"], 79, 42),
  mk("a162", "Count all subsequences with sum K", "GeeksforGeeks", "Medium", "https://bit.ly/3SVf1me", "Recursion", ["Step 7.2 Subsequences Pattern"], 78, 43),
  mk("a163", "Check if there exists a subsequence with sum K", "GeeksforGeeks", "Medium", "https://bit.ly/3SVf1me", "Recursion", ["Step 7.2 Subsequences Pattern"], 77, 44),
  mk("a164", "Combination Sum", "LeetCode", "Medium", "https://leetcode.com/problems/combination-sum/", "Recursion", ["Step 7.2 Subsequences Pattern"], 81, 45),
  mk("a165", "Combination Sum-II", "LeetCode", "Medium", "https://leetcode.com/problems/combination-sum-ii/", "Recursion", ["Step 7.2 Subsequences Pattern"], 80, 46),
  mk("a166", "Subset Sum-I", "GeeksforGeeks", "Medium", "https://bit.ly/3C9GQRS", "Recursion", ["Step 7.2 Subsequences Pattern"], 74, 47),
  mk("a167", "Subset Sum-II", "LeetCode", "Medium", "https://leetcode.com/problems/subsets-ii/", "Recursion", ["Step 7.2 Subsequences Pattern"], 78, 48),
  mk("a168", "Combination Sum – III", "LeetCode", "Medium", "https://leetcode.com/problems/combination-sum-iii/", "Recursion", ["Step 7.2 Subsequences Pattern"], 77, 49),
  mk("a169", "Letter Combinations of a Phone number", "LeetCode", "Medium", "https://leetcode.com/problems/letter-combinations-of-a-phone-number/", "Recursion", ["Step 7.2 Subsequences Pattern"], 76, 50),
  mk("a170", "Palindrome Partitioning", "LeetCode", "Hard", "https://leetcode.com/problems/palindrome-partitioning/", "Recursion", ["Step 7.3 Trying out all Combos / Hard"], 75, 51),
  mk("a171", "Word Search", "LeetCode", "Hard", "https://leetcode.com/problems/word-search/", "Recursion", ["Step 7.3 Trying out all Combos / Hard"], 74, 52),
  mk("a172", "N Queen", "LeetCode", "Hard", "https://leetcode.com/problems/n-queens/", "Recursion", ["Step 7.3 Trying out all Combos / Hard"], 73, 53),
  mk("a173", "Rat in a Maze", "GeeksforGeeks", "Hard", "https://bit.ly/3pkqK0g", "Recursion", ["Step 7.3 Trying out all Combos / Hard"], 67, 54),
  mk("a174", "Word Break", "LeetCode", "Hard", "https://leetcode.com/problems/word-break/", "Recursion", ["Step 7.3 Trying out all Combos / Hard"], 71, 55),
  mk("a175", "M Coloring Problem", "GeeksforGeeks", "Hard", "https://bit.ly/3Cepqnv", "Recursion", ["Step 7.3 Trying out all Combos / Hard"], 65, 56),
  mk("a176", "Sudoko Solver", "LeetCode", "Hard", "https://leetcode.com/problems/sudoku-solver/", "Recursion", ["Step 7.3 Trying out all Combos / Hard"], 69, 57),
  mk("a177", "Expression Add Operators", "LeetCode", "Hard", "https://leetcode.com/problems/expression-add-operators/", "Recursion", ["Step 7.3 Trying out all Combos / Hard"], 68, 58),
  mk("a178", "Introduction to Bit Manipulation [Theory]", "GeeksforGeeks", "Medium", "https://bit.ly/3Eo8JVW", "Bit Manipulation", ["Step 8.1 Learn Bit Manipulation"], 62, 59),
  mk("a179", "Check if the i-th bit is set or not", "GeeksforGeeks", "Medium", "https://bit.ly/3C0kAJR", "Bit Manipulation", ["Step 8.1 Learn Bit Manipulation"], 61, 60),
  mk("a180", "Check if a number is odd or not", "GeeksforGeeks", "Medium", "https://bit.ly/3xDMLvF", "Bit Manipulation", ["Step 8.1 Learn Bit Manipulation"], 90, 1),
  mk("a181", "Check if a number is power of 2 or not", "LeetCode", "Medium", "https://leetcode.com/problems/power-of-two/", "Bit Manipulation", ["Step 8.1 Learn Bit Manipulation"], 94, 2),
  mk("a182", "Count the number of set bits", "GeeksforGeeks", "Medium", "https://bit.ly/3SbiBZ2", "Bit Manipulation", ["Step 8.1 Learn Bit Manipulation"], 88, 3),
  mk("a183", "Set/Unset the rightmost unset bit", "GeeksforGeeks", "Medium", "https://bit.ly/3Sq66IM", "Bit Manipulation", ["Step 8.1 Learn Bit Manipulation"], 87, 4),
  mk("a184", "Swap two numbers", "GeeksforGeeks", "Medium", "https://bit.ly/3qVixAz", "Bit Manipulation", ["Step 8.1 Learn Bit Manipulation"], 86, 5),
  mk("a185", "Divide two integers without using multiplication, division and mod operator", "LeetCode", "Medium", "https://leetcode.com/problems/divide-two-integers/", "Bit Manipulation", ["Step 8.1 Learn Bit Manipulation"], 90, 6),
  mk("a186", "Count number of bits to be flipped to convert A to B", "LeetCode", "Medium", "https://leetcode.com/problems/minimum-bit-flips-to-convert-number/", "Bit Manipulation", ["Step 8.2 Interview Problems"], 89, 7),
  mk("a187", "Find the number that appears odd number of times", "LeetCode", "Medium", "https://leetcode.com/problems/single-number/", "Bit Manipulation", ["Step 8.2 Interview Problems"], 88, 8),
  mk("a188", "Power Set", "LeetCode", "Medium", "https://leetcode.com/problems/subsets/", "Bit Manipulation", ["Step 8.2 Interview Problems"], 87, 9),
  mk("a189", "Fnd xor of numbers from L to R", "GeeksforGeeks", "Medium", "https://bit.ly/3T8xUCf", "Bit Manipulation", ["Step 8.2 Interview Problems"], 81, 10),
  mk("a190", "Find the two numbers appearing odd number of times", "GeeksforGeeks", "Medium", "https://bit.ly/3DK7O3i", "Bit Manipulation", ["Step 8.2 Interview Problems"], 80, 11),
  mk("a191", "Implement Stack using Arrays", "GeeksforGeeks", "Medium", "https://bit.ly/3QPJ39w", "Stack and Queues", ["Step 9.1 Learning"], 79, 12),
  mk("a192", "Implement Queue using Arrays", "GeeksforGeeks", "Medium", "https://bit.ly/3C9HLli", "Stack and Queues", ["Step 9.1 Learning"], 78, 13),
  mk("a193", "Implement Stack using Queue", "LeetCode", "Medium", "https://leetcode.com/problems/implement-stack-using-queues/", "Stack and Queues", ["Step 9.1 Learning"], 82, 14),
  mk("a194", "Implement Queue using Stack", "LeetCode", "Medium", "https://leetcode.com/problems/implement-queue-using-stacks/", "Stack and Queues", ["Step 9.1 Learning"], 81, 15),
  mk("a195", "Implement stack usingLinkedlist", "GeeksforGeeks", "Medium", "https://bit.ly/3w6PwVv", "Stack and Queues", ["Step 9.1 Learning"], 75, 16),
  mk("a196", "Implement queue usingLinkedlist", "GeeksforGeeks", "Medium", "https://bit.ly/3PA7mY0", "Stack and Queues", ["Step 9.1 Learning"], 74, 17),
  mk("a197", "Check for balanced paranthesis", "LeetCode", "Medium", "https://leetcode.com/problems/valid-parentheses/", "Stack and Queues", ["Step 9.1 Learning"], 78, 18),
  mk("a198", "Implement Min Stack", "LeetCode", "Medium", "https://leetcode.com/problems/min-stack/", "Stack and Queues", ["Step 9.1 Learning"], 77, 19),
  mk("a199", "Infix to Postfix Conversion using Stack", "GeeksforGeeks", "Medium", "https://bit.ly/3JWYj1P", "Stack and Queues", ["Step 9.2 Prefix, Infix, PostFix Conversion Problems"], 71, 20),
  mk("a200", "Prefix to Infix Conversion", "GeeksforGeeks", "Medium", "https://bit.ly/3FwxK3j", "Stack and Queues", ["Step 9.2 Prefix, Infix, PostFix Conversion Problems"], 70, 21),
  mk("a201", "Prefix to Postfix Conversion", "GeeksforGeeks", "Medium", "https://bit.ly/3DrwCLI", "Stack and Queues", ["Step 9.2 Prefix, Infix, PostFix Conversion Problems"], 69, 22),
  mk("a202", "Postfix to Prefix Conversion", "GeeksforGeeks", "Medium", "https://bit.ly/3UaWJxk", "Stack and Queues", ["Step 9.2 Prefix, Infix, PostFix Conversion Problems"], 68, 23),
  mk("a203", "Postfix to Infix", "GeeksforGeeks", "Medium", "https://bit.ly/3sNZ1a2", "Stack and Queues", ["Step 9.2 Prefix, Infix, PostFix Conversion Problems"], 67, 24),
  mk("a204", "Convert Infix To Prefix Notation", "GeeksforGeeks", "Medium", "https://bit.ly/3T0gZ4P", "Stack and Queues", ["Step 9.2 Prefix, Infix, PostFix Conversion Problems"], 66, 25),
  mk("a205", "Next Greater Element", "LeetCode", "Medium", "https://leetcode.com/problems/next-greater-element-i/", "Stack and Queues", ["Step 9.3 Monotonic Stack/Queue Problems [VVV. Imp]"], 70, 26),
  mk("a206", "Next Greater Element 2", "LeetCode", "Medium", "https://leetcode.com/problems/next-greater-element-ii/", "Stack and Queues", ["Step 9.3 Monotonic Stack/Queue Problems [VVV. Imp]"], 69, 27),
  mk("a207", "Next Smaller Element", "GeeksforGeeks", "Medium", "https://bit.ly/3wbhcIL", "Stack and Queues", ["Step 9.3 Monotonic Stack/Queue Problems [VVV. Imp]"], 63, 28),
  mk("a208", "Number of NGEs to the right", "GeeksforGeeks", "Medium", "https://bit.ly/3Np2R2H", "Stack and Queues", ["Step 9.3 Monotonic Stack/Queue Problems [VVV. Imp]"], 62, 29),
  mk("a209", "Trapping Rainwater", "LeetCode", "Medium", "https://leetcode.com/problems/trapping-rain-water/", "Stack and Queues", ["Step 9.3 Monotonic Stack/Queue Problems [VVV. Imp]"], 66, 30),
  mk("a210", "Sum of subarray minimum", "LeetCode", "Medium", "https://leetcode.com/problems/sum-of-subarray-minimums/", "Stack and Queues", ["Step 9.3 Monotonic Stack/Queue Problems [VVV. Imp]"], 95, 31),
  mk("a211", "Stock span problem", "LeetCode", "Medium", "https://leetcode.com/problems/online-stock-span/", "Stack and Queues", ["Step 9.3 Monotonic Stack/Queue Problems [VVV. Imp]"], 94, 32),
  mk("a212", "Asteroid Collision", "LeetCode", "Medium", "https://leetcode.com/problems/asteroid-collision/", "Stack and Queues", ["Step 9.3 Monotonic Stack/Queue Problems [VVV. Imp]"], 93, 33),
  mk("a213", "Sum of subarray ranges", "LeetCode", "Medium", "https://leetcode.com/problems/sum-of-subarray-ranges/", "Stack and Queues", ["Step 9.3 Monotonic Stack/Queue Problems [VVV. Imp]"], 92, 34),
  mk("a214", "Remove k Digits", "LeetCode", "Medium", "https://leetcode.com/problems/remove-k-digits/", "Stack and Queues", ["Step 9.3 Monotonic Stack/Queue Problems [VVV. Imp]"], 91, 35),
  mk("a215", "Largest rectangle in a histogram", "LeetCode", "Medium", "https://leetcode.com/problems/largest-rectangle-in-histogram/", "Stack and Queues", ["Step 9.3 Monotonic Stack/Queue Problems [VVV. Imp]"], 90, 36),
  mk("a216", "Maximal Rectangles", "LeetCode", "Medium", "https://leetcode.com/problems/maximal-rectangle/", "Stack and Queues", ["Step 9.3 Monotonic Stack/Queue Problems [VVV. Imp]"], 89, 37),
  mk("a217", "Sliding Window maximum", "LeetCode", "Medium", "https://leetcode.com/problems/sliding-window-maximum/", "Stack and Queues", ["Step 9.4 Implementation Problems"], 88, 38),
  mk("a218", "Stock Span Problem", "LeetCode", "Medium", "https://leetcode.com/problems/online-stock-span/", "Stack and Queues", ["Step 9.4 Implementation Problems"], 87, 39),
  mk("a219", "The Celebrity Problem", "LeetCode", "Medium", "https://leetcode.com/accounts/login/?next=/problems/find-the-celebrity/", "Stack and Queues", ["Step 9.4 Implementation Problems"], 86, 40),
  mk("a220", "Rotten Oranges", "LeetCode", "Medium", "https://leetcode.com/problems/rotting-oranges/", "Stack and Queues", ["Step 9.4 Implementation Problems"], 85, 41),
  mk("a221", "LRU cache (IMPORTANT)", "LeetCode", "Medium", "https://leetcode.com/problems/lru-cache/", "Stack and Queues", ["Step 9.4 Implementation Problems"], 84, 42),
  mk("a222", "LFU cache", "LeetCode", "Medium", "https://leetcode.com/problems/lfu-cache/", "Stack and Queues", ["Step 9.4 Implementation Problems"], 83, 43),
  mk("a223", "Longest Substring Without Repeating Characters", "LeetCode", "Medium", "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "Sliding Window & Two Pointers", ["Step 10.1 Medium Problems"], 82, 44),
  mk("a224", "Max Consecutive Ones III", "LeetCode", "Medium", "https://leetcode.com/problems/max-consecutive-ones-iii/", "Sliding Window & Two Pointers", ["Step 10.1 Medium Problems"], 81, 45),
  mk("a225", "Fruit Into Baskets", "GeeksforGeeks", "Medium", "https://bit.ly/3D6d94w", "Sliding Window & Two Pointers", ["Step 10.1 Medium Problems"], 75, 46),
  mk("a226", "longest repeating character replacement", "LeetCode", "Medium", "https://leetcode.com/problems/longest-repeating-character-replacement/", "Sliding Window & Two Pointers", ["Step 10.1 Medium Problems"], 79, 47),
  mk("a227", "Binary subarray with sum", "LeetCode", "Medium", "https://leetcode.com/problems/binary-subarrays-with-sum/", "Sliding Window & Two Pointers", ["Step 10.1 Medium Problems"], 78, 48),
  mk("a228", "Count number of nice subarrays", "LeetCode", "Medium", "https://leetcode.com/problems/count-number-of-nice-subarrays/", "Sliding Window & Two Pointers", ["Step 10.1 Medium Problems"], 77, 49),
  mk("a229", "Number of substring containing all three characters", "LeetCode", "Medium", "https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/", "Sliding Window & Two Pointers", ["Step 10.1 Medium Problems"], 76, 50),
  mk("a230", "Maximum point you can obtain from cards", "LeetCode", "Medium", "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/", "Sliding Window & Two Pointers", ["Step 10.1 Medium Problems"], 75, 51),
  mk("a231", "Longest Substring with At Most K Distinct Characters", "LeetCode", "Hard", "https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/", "Sliding Window & Two Pointers", ["Step 10.2 Hard Problems"], 74, 52),
  mk("a232", "Minimum Window Substring", "LeetCode", "Hard", "https://leetcode.com/problems/minimum-window-substring/", "Sliding Window & Two Pointers", ["Step 10.2 Hard Problems"], 73, 53),
  mk("a233", "Minimum Window Subsequence", "LeetCode", "Hard", "https://leetcode.com/problems/minimum-window-subsequence/", "Sliding Window & Two Pointers", ["Step 10.2 Hard Problems"], 72, 54),
  mk("a234", "Introduction to Priority Queues using Binary Heaps", "GeeksforGeeks", "Medium", "https://bit.ly/3TSxAHd", "Heaps", ["Step 11.1 Learning"], 66, 55),
  mk("a235", "Min Heap and Max Heap Implementation", "GeeksforGeeks", "Medium", "https://bit.ly/3weGgP3", "Heaps", ["Step 11.1 Learning"], 65, 56),
  mk("a236", "Check if an array represents a min-heap or not", "GeeksforGeeks", "Medium", "https://bit.ly/3AbFrrI", "Heaps", ["Step 11.1 Learning"], 64, 57),
  mk("a237", "Convert min Heap to max Heap", "GeeksforGeeks", "Medium", "https://bit.ly/3flmw7c", "Heaps", ["Step 11.1 Learning"], 63, 58),
  mk("a238", "Kth largest element in an array [use priority queue]", "LeetCode", "Medium", "https://leetcode.com/problems/kth-largest-element-in-an-array/", "Heaps", ["Step 11.2 Medium Problems"], 67, 59),
  mk("a239", "Kth smallest element in an array [use priority queue]", "GeeksforGeeks", "Medium", "https://bit.ly/3PvAOhK", "Heaps", ["Step 11.2 Medium Problems"], 61, 60),
  mk("a240", "Sort K sorted array", "GeeksforGeeks", "Medium", "https://bit.ly/3QLpaAs", "Heaps", ["Step 11.2 Medium Problems"], 90, 1),
  mk("a241", "Merge M sorted Lists", "LeetCode", "Medium", "https://leetcode.com/problems/merge-k-sorted-lists/", "Heaps", ["Step 11.2 Medium Problems"], 94, 2),
  mk("a242", "Replace each array element by its corresponding rank", "GeeksforGeeks", "Medium", "https://bit.ly/3TS3jcg", "Heaps", ["Step 11.2 Medium Problems"], 88, 3),
  mk("a243", "Task Scheduler", "LeetCode", "Medium", "https://leetcode.com/problems/task-scheduler/", "Heaps", ["Step 11.2 Medium Problems"], 92, 4),
  mk("a244", "Hands of Straights", "LeetCode", "Medium", "https://leetcode.com/problems/hand-of-straights/", "Heaps", ["Step 11.2 Medium Problems"], 91, 5),
  mk("a245", "Design twitter", "LeetCode", "Hard", "https://leetcode.com/problems/design-twitter/", "Heaps", ["Step 11.3 Hard Problems"], 90, 6),
  mk("a246", "Kth largest element in a stream of running integers", "LeetCode", "Hard", "https://leetcode.com/problems/kth-largest-element-in-a-stream/#:~:text=Implement%20KthLargest%20class%3A,largest%20element%20in%20the%20stream.", "Heaps", ["Step 11.3 Hard Problems"], 89, 7),
  mk("a247", "Maximum Sum Combination", "GeeksforGeeks", "Hard", "https://bit.ly/3sSXvTT", "Heaps", ["Step 11.3 Hard Problems"], 83, 8),
  mk("a248", "Find Median from Data Stream", "LeetCode", "Hard", "https://leetcode.com/problems/find-median-from-data-stream/", "Heaps", ["Step 11.3 Hard Problems"], 87, 9),
  mk("a249", "K most frequent elements", "LeetCode", "Hard", "https://leetcode.com/problems/top-k-frequent-elements/", "Heaps", ["Step 11.3 Hard Problems"], 86, 10),
  mk("a250", "Assign Cookies", "LeetCode", "Easy", "https://leetcode.com/problems/assign-cookies/", "Greedy Algorithms", ["Step 12.1 Easy Problems"], 85, 11),
  mk("a251", "Fractional Knapsack Problem", "GeeksforGeeks", "Easy", "https://bit.ly/3PsqOFL", "Greedy Algorithms", ["Step 12.1 Easy Problems"], 79, 12),
  mk("a252", "Greedy algorithm to find minimum number of coins", "GeeksforGeeks", "Easy", "https://bit.ly/3Ka7xYU", "Greedy Algorithms", ["Step 12.1 Easy Problems"], 78, 13),
  mk("a253", "Lemonade Change", "LeetCode", "Easy", "https://leetcode.com/problems/lemonade-change/", "Greedy Algorithms", ["Step 12.1 Easy Problems"], 82, 14),
  mk("a254", "Valid Paranthesis Checker", "LeetCode", "Easy", "https://leetcode.com/problems/valid-parenthesis-string/", "Greedy Algorithms", ["Step 12.1 Easy Problems"], 81, 15),
  mk("a255", "N meetings in one room", "GeeksforGeeks", "Hard", "https://bit.ly/3A6Ob1Y", "Greedy Algorithms", ["Step 12.2 Medium/Hard"], 75, 16),
  mk("a256", "Jump Game", "LeetCode", "Hard", "https://leetcode.com/problems/jump-game/", "Greedy Algorithms", ["Step 12.2 Medium/Hard"], 79, 17),
  mk("a257", "Jump Game 2", "LeetCode", "Hard", "https://leetcode.com/problems/jump-game-ii/", "Greedy Algorithms", ["Step 12.2 Medium/Hard"], 78, 18),
  mk("a258", "Minimum number of platforms required for a railway", "GeeksforGeeks", "Hard", "https://bit.ly/3bXX5Hm", "Greedy Algorithms", ["Step 12.2 Medium/Hard"], 72, 19),
  mk("a259", "Job sequencing Problem", "GeeksforGeeks", "Hard", "https://bit.ly/3Pttpzj", "Greedy Algorithms", ["Step 12.2 Medium/Hard"], 71, 20),
  mk("a260", "Candy", "LeetCode", "Hard", "https://leetcode.com/problems/candy/", "Greedy Algorithms", ["Step 12.2 Medium/Hard"], 75, 21),
  mk("a261", "Program for Shortest Job First (or SJF) CPU Scheduling", "GeeksforGeeks", "Hard", "https://bit.ly/3DYCIFb", "Greedy Algorithms", ["Step 12.2 Medium/Hard"], 69, 22),
  mk("a262", "Program for Least Recently Used (LRU) Page Replacement Algorithm", "GeeksforGeeks", "Hard", "https://bit.ly/3dtFqHG", "Greedy Algorithms", ["Step 12.2 Medium/Hard"], 68, 23),
  mk("a263", "Insert Interval", "LeetCode", "Hard", "https://leetcode.com/problems/insert-interval/", "Greedy Algorithms", ["Step 12.2 Medium/Hard"], 72, 24),
  mk("a264", "Merge Intervals", "LeetCode", "Hard", "https://leetcode.com/problems/merge-intervals/", "Greedy Algorithms", ["Step 12.2 Medium/Hard"], 71, 25),
  mk("a265", "Non-overlapping Intervals", "LeetCode", "Hard", "https://leetcode.com/problems/non-overlapping-intervals/", "Greedy Algorithms", ["Step 12.2 Medium/Hard"], 70, 26),
  mk("a266", "Introduction to Trees", "GeeksforGeeks", "Medium", "https://bit.ly/3EsRmTM", "Binary Trees", ["Step 13.1 Traversals"], 64, 27),
  mk("a267", "Binary Tree Representation in C++", "GeeksforGeeks", "Medium", "https://bit.ly/3gn5Soh", "Binary Trees", ["Step 13.1 Traversals"], 63, 28),
  mk("a268", "Binary Tree Representation in Java", "GeeksforGeeks", "Medium", "https://bit.ly/3gn5Soh", "Binary Trees", ["Step 13.1 Traversals"], 62, 29),
  mk("a269", "Binary Tree Traversals in Binary Tree", "GeeksforGeeks", "Medium", "https://bit.ly/3Cb4VIh", "Binary Trees", ["Step 13.1 Traversals"], 61, 30),
  mk("a270", "Preorder Traversal of Binary Tree", "LeetCode", "Medium", "https://leetcode.com/problems/binary-tree-preorder-traversal/", "Binary Trees", ["Step 13.1 Traversals"], 95, 31),
  mk("a271", "Inorder Traversal of Binary Tree", "LeetCode", "Medium", "https://leetcode.com/problems/binary-tree-inorder-traversal/", "Binary Trees", ["Step 13.1 Traversals"], 94, 32),
  mk("a272", "Post-order Traversal of Binary Tree", "LeetCode", "Medium", "https://leetcode.com/problems/binary-tree-postorder-traversal/", "Binary Trees", ["Step 13.1 Traversals"], 93, 33),
  mk("a273", "Level order Traversal / Level order traversal in spiral form", "LeetCode", "Medium", "https://leetcode.com/problems/binary-tree-level-order-traversal/", "Binary Trees", ["Step 13.1 Traversals"], 92, 34),
  mk("a274", "Iterative Preorder Traversal of Binary Tree", "LeetCode", "Medium", "https://leetcode.com/problems/binary-tree-preorder-traversal/", "Binary Trees", ["Step 13.1 Traversals"], 91, 35),
  mk("a275", "Iterative Inorder Traversal of Binary Tree", "LeetCode", "Medium", "https://leetcode.com/problems/binary-tree-inorder-traversal/", "Binary Trees", ["Step 13.1 Traversals"], 90, 36),
  mk("a276", "Post-order Traversal of Binary Tree using 2 stack", "LeetCode", "Medium", "https://leetcode.com/problems/binary-tree-postorder-traversal/", "Binary Trees", ["Step 13.1 Traversals"], 89, 37),
  mk("a277", "Post-order Traversal of Binary Tree using 1 stack", "LeetCode", "Medium", "https://leetcode.com/problems/binary-tree-postorder-traversal/", "Binary Trees", ["Step 13.1 Traversals"], 88, 38),
  mk("a278", "Preorder, Inorder, and Postorder Traversal in one Traversal", "GeeksforGeeks", "Medium", "https://bit.ly/3T3oW9M", "Binary Trees", ["Step 13.1 Traversals"], 82, 39),
  mk("a279", "Height of a Binary Tree", "LeetCode", "Medium", "https://leetcode.com/problems/maximum-depth-of-binary-tree/", "Binary Trees", ["Step 13.2 Medium Problems"], 86, 40),
  mk("a280", "Check if the Binary tree is height-balanced or not", "LeetCode", "Medium", "https://leetcode.com/problems/balanced-binary-tree/", "Binary Trees", ["Step 13.2 Medium Problems"], 85, 41),
  mk("a281", "Diameter of Binary Tree", "LeetCode", "Medium", "https://leetcode.com/problems/diameter-of-binary-tree/", "Binary Trees", ["Step 13.2 Medium Problems"], 84, 42),
  mk("a282", "Maximum path sum", "LeetCode", "Medium", "https://leetcode.com/problems/binary-tree-maximum-path-sum/", "Binary Trees", ["Step 13.2 Medium Problems"], 83, 43),
  mk("a283", "Check if two trees are identical or not", "LeetCode", "Medium", "https://leetcode.com/problems/same-tree/", "Binary Trees", ["Step 13.2 Medium Problems"], 82, 44),
  mk("a284", "Zig Zag Traversal of Binary Tree", "LeetCode", "Medium", "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", "Binary Trees", ["Step 13.2 Medium Problems"], 81, 45),
  mk("a285", "Boundary Traversal of Binary Tree", "LeetCode", "Medium", "https://leetcode.com/problems/boundary-of-binary-tree/", "Binary Trees", ["Step 13.2 Medium Problems"], 80, 46),
  mk("a286", "Vertical Order Traversal of Binary Tree", "LeetCode", "Medium", "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/", "Binary Trees", ["Step 13.2 Medium Problems"], 79, 47),
  mk("a287", "Top View of Binary Tree", "GeeksforGeeks", "Medium", "https://bit.ly/3PsvE5T", "Binary Trees", ["Step 13.2 Medium Problems"], 73, 48),
  mk("a288", "Bottom View of Binary Tree", "GeeksforGeeks", "Medium", "https://bit.ly/3Asftl0", "Binary Trees", ["Step 13.2 Medium Problems"], 72, 49),
  mk("a289", "Right/Left View of Binary Tree", "LeetCode", "Medium", "https://leetcode.com/problems/binary-tree-right-side-view/", "Binary Trees", ["Step 13.2 Medium Problems"], 76, 50),
  mk("a290", "Symmetric Binary Tree", "LeetCode", "Medium", "https://leetcode.com/problems/symmetric-tree/", "Binary Trees", ["Step 13.2 Medium Problems"], 75, 51),
  mk("a291", "Root to Node Path in Binary Tree", "GeeksforGeeks", "Hard", "https://bit.ly/3QA600D", "Binary Trees", ["Step 13.1 Hard Problems"], 69, 52),
  mk("a292", "LCA in Binary Tree", "LeetCode", "Hard", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", "Binary Trees", ["Step 13.1 Hard Problems"], 73, 53),
  mk("a293", "Maximum width of a Binary Tree", "LeetCode", "Hard", "https://leetcode.com/problems/maximum-width-of-binary-tree/", "Binary Trees", ["Step 13.1 Hard Problems"], 72, 54),
  mk("a294", "Check for Children Sum Property", "GeeksforGeeks", "Hard", "https://bit.ly/3dEr73g", "Binary Trees", ["Step 13.1 Hard Problems"], 66, 55),
  mk("a295", "Print all the Nodes at a distance of K in a Binary Tree", "LeetCode", "Hard", "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/", "Binary Trees", ["Step 13.1 Hard Problems"], 70, 56),
  mk("a296", "Minimum time taken to BURN the Binary Tree from a Node", "GeeksforGeeks", "Hard", "https://bit.ly/3wcg7k1", "Binary Trees", ["Step 13.1 Hard Problems"], 64, 57),
  mk("a297", "Count total Nodes in a COMPLETE Binary Tree", "LeetCode", "Hard", "https://leetcode.com/problems/count-complete-tree-nodes/", "Binary Trees", ["Step 13.1 Hard Problems"], 68, 58),
  mk("a298", "Requirements needed to construct a Unique Binary Tree | Theory", "GeeksforGeeks", "Hard", "https://bit.ly/3UVCR1U", "Binary Trees", ["Step 13.1 Hard Problems"], 62, 59),
  mk("a299", "Construct Binary Tree from inorder and preorder", "LeetCode", "Hard", "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", "Binary Trees", ["Step 13.1 Hard Problems"], 66, 60),
  mk("a300", "Serialize and deserialize Binary Tree", "LeetCode", "Hard", "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", "Binary Trees", ["Step 13.1 Hard Problems"], 95, 1),
  mk("a301", "Morris Preorder Traversal of a Binary Tree", "LeetCode", "Hard", "https://leetcode.com/problems/binary-tree-inorder-traversal/", "Binary Trees", ["Step 13.1 Hard Problems"], 94, 2),
  mk("a302", "Morris Inorder Traversal of a Binary Tree", "LeetCode", "Hard", "https://leetcode.com/problems/binary-tree-inorder-traversal/", "Binary Trees", ["Step 13.1 Hard Problems"], 93, 3),
  mk("a303", "Flatten Binary Tree toLinkedList", "LeetCode", "Hard", "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", "Binary Trees", ["Step 13.1 Hard Problems"], 92, 4),
  mk("a304", "Introduction to Binary Search Tree", "GeeksforGeeks", "Medium", "https://bit.ly/3gprRLk", "Binary Search Trees", ["Step 14.1 Concepts"], 86, 5),
  mk("a305", "Search in a Binary Search Tree", "LeetCode", "Medium", "https://leetcode.com/problems/search-in-a-binary-search-tree/", "Binary Search Trees", ["Step 14.1 Concepts"], 90, 6),
  mk("a306", "Find Min/Max in BST", "GeeksforGeeks", "Medium", "https://bit.ly/3f9XkzZ", "Binary Search Trees", ["Step 14.1 Concepts"], 84, 7),
  mk("a307", "Ceil in a Binary Search Tree", "GeeksforGeeks", "Medium", "https://bit.ly/3BULqTJ", "Binary Search Trees", ["Step 14.2 Practice Problems"], 83, 8),
  mk("a308", "Floor in a Binary Search Tree", "GeeksforGeeks", "Medium", "https://bit.ly/3TSbXXE", "Binary Search Trees", ["Step 14.2 Practice Problems"], 82, 9),
  mk("a309", "Insert a given Node in Binary Search Tree", "LeetCode", "Medium", "https://leetcode.com/problems/insert-into-a-binary-search-tree/", "Binary Search Trees", ["Step 14.2 Practice Problems"], 86, 10),
  mk("a310", "Delete a Node in Binary Search Tree", "LeetCode", "Medium", "https://leetcode.com/problems/delete-node-in-a-bst/", "Binary Search Trees", ["Step 14.2 Practice Problems"], 85, 11),
  mk("a311", "Find K-th smallest/largest element in BST", "LeetCode", "Medium", "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", "Binary Search Trees", ["Step 14.2 Practice Problems"], 84, 12),
  mk("a312", "Check if a tree is a BST or BT", "LeetCode", "Medium", "https://leetcode.com/problems/validate-binary-search-tree/", "Binary Search Trees", ["Step 14.2 Practice Problems"], 83, 13),
  mk("a313", "LCA in Binary Search Tree", "LeetCode", "Medium", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", "Binary Search Trees", ["Step 14.2 Practice Problems"], 82, 14),
  mk("a314", "Construct a BST from a preorder traversal", "LeetCode", "Medium", "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/", "Binary Search Trees", ["Step 14.2 Practice Problems"], 81, 15),
  mk("a315", "Inorder Successor/Predecessor in BST", "LeetCode", "Medium", "https://leetcode.com/problems/inorder-successor-in-bst/", "Binary Search Trees", ["Step 14.2 Practice Problems"], 80, 16),
  mk("a316", "Merge 2 BST’s", "LeetCode", "Medium", "https://leetcode.com/problems/binary-search-tree-iterator/", "Binary Search Trees", ["Step 14.2 Practice Problems"], 79, 17),
  mk("a317", "Two Sum In BST | Check if there exists a pair with Sum K", "LeetCode", "Medium", "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/", "Binary Search Trees", ["Step 14.2 Practice Problems"], 78, 18),
  mk("a318", "Recover BST | Correct BST with two nodes swapped", "LeetCode", "Medium", "https://leetcode.com/problems/recover-binary-search-tree/", "Binary Search Trees", ["Step 14.2 Practice Problems"], 77, 19),
  mk("a319", "Largest BST in Binary Tree", "GeeksforGeeks", "Medium", "https://bit.ly/3LxECPd", "Binary Search Trees", ["Step 14.2 Practice Problems"], 71, 20),
  mk("a320", "Graph and Types", "GeeksforGeeks", "Medium", "https://bit.ly/3gpY19t", "Graphs", ["Step 15.1 Learning"], 70, 21),
  mk("a321", "Graph Representation | C++", "GeeksforGeeks", "Medium", "https://bit.ly/3dGuwyv", "Graphs", ["Step 15.1 Learning"], 69, 22),
  mk("a322", "Graph Representation | Java", "GeeksforGeeks", "Medium", "https://bit.ly/3dGuwyv", "Graphs", ["Step 15.1 Learning"], 68, 23),
  mk("a323", "Connected Components | Logic Explanation", "GeeksforGeeks", "Medium", "https://bit.ly/3AxzhDG", "Graphs", ["Step 15.1 Learning"], 67, 24),
  mk("a324", "BFS", "GeeksforGeeks", "Medium", "https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1?utm_source=youtube&amp;utm_medium=collab_striver_ytdescription&amp;utm_campaign=bfs_of_graph", "Graphs", ["Step 15.1 Learning"], 66, 25),
  mk("a325", "DFS", "GeeksforGeeks", "Medium", "https://practice.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1?utm_source=youtube&amp;utm_medium=collab_striver_ytdescription&amp;utm_campaign=dfs_of_graph", "Graphs", ["Step 15.1 Learning"], 65, 26),
  mk("a326", "Number of provinces (leetcode)", "LeetCode", "Medium", "https://leetcode.com/problems/number-of-provinces/#:~:text=A%20province%20is%20a%20group,the%20total%20number%20of%20provinces.", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 69, 27),
  mk("a327", "Connected Components Problem in Matrix", "GeeksforGeeks", "Medium", "https://bit.ly/3AxzhDG", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 63, 28),
  mk("a328", "Rotten Oranges", "LeetCode", "Medium", "https://leetcode.com/problems/rotting-oranges/", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 67, 29),
  mk("a329", "Flood fill", "LeetCode", "Medium", "https://leetcode.com/problems/flood-fill/", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 66, 30),
  mk("a330", "Cycle Detection in unirected Graph (bfs)", "GeeksforGeeks", "Medium", "https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1?utm_source=youtube&amp;utm_medium=collab_striver_ytdescription&amp;utm_campaign=detect-cycle-in-an-undirected-graph", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 90, 31),
  mk("a331", "Cycle Detection in undirected Graph (dfs)", "GeeksforGeeks", "Medium", "https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1?utm_source=youtube&amp;utm_medium=collab_striver_ytdescription&amp;utm_campaign=detect-cycle-in-an-undirected-graph", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 89, 32),
  mk("a332", "0/1 Matrix (Bfs Problem)", "LeetCode", "Medium", "https://leetcode.com/problems/01-matrix/", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 93, 33),
  mk("a333", "Surrounded Regions (dfs)", "LeetCode", "Medium", "https://leetcode.com/problems/surrounded-regions/", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 92, 34),
  mk("a334", "Number of Enclaves [flood fill implementation – multisource]", "LeetCode", "Medium", "https://leetcode.com/problems/number-of-enclaves/", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 91, 35),
  mk("a335", "Word ladder – 1", "LeetCode", "Medium", "https://leetcode.com/problems/word-ladder/", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 90, 36),
  mk("a336", "Word ladder – 2", "LeetCode", "Medium", "https://leetcode.com/problems/word-ladder-ii/", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 89, 37),
  mk("a337", "Number of Distinct Islands [dfs multisource]", "LeetCode", "Medium", "https://leetcode.com/problems/number-of-distinct-islands-ii/", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 88, 38),
  mk("a338", "Bipartite Graph (DFS)", "LeetCode", "Medium", "https://leetcode.com/problems/is-graph-bipartite/", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 87, 39),
  mk("a339", "Cycle Detection in Directed Graph (DFS)", "LeetCode", "Medium", "https://leetcode.com/problems/course-schedule-ii/discuss/293048/detecting-cycle-in-directed-graph-problem", "Graphs", ["Step 15.2 Problems on BFS/DFS"], 86, 40),
  mk("a340", "Topo Sort", "GeeksforGeeks", "Medium", "https://bit.ly/3S02dKC", "Graphs", ["Step 15.3 Topo Sort and Problems"], 80, 41),
  mk("a341", "Kahn’s Algorithm", "GeeksforGeeks", "Medium", "https://bit.ly/3c690mm", "Graphs", ["Step 15.3 Topo Sort and Problems"], 79, 42),
  mk("a342", "Cycle Detection in Directed Graph (BFS)", "GeeksforGeeks", "Medium", "https://bit.ly/3DK3elS", "Graphs", ["Step 15.3 Topo Sort and Problems"], 78, 43),
  mk("a343", "Course Schedule – I", "LeetCode", "Medium", "https://leetcode.com/problems/course-schedule/", "Graphs", ["Step 15.3 Topo Sort and Problems"], 82, 44),
  mk("a344", "Course Schedule – II", "LeetCode", "Medium", "https://leetcode.com/problems/course-schedule-ii/", "Graphs", ["Step 15.3 Topo Sort and Problems"], 81, 45),
  mk("a345", "Find eventual safe states", "LeetCode", "Medium", "https://leetcode.com/problems/find-eventual-safe-states/", "Graphs", ["Step 15.3 Topo Sort and Problems"], 80, 46),
  mk("a346", "Alien dictionary", "LeetCode", "Medium", "https://leetcode.com/problems/alien-dictionary/solution/", "Graphs", ["Step 15.3 Topo Sort and Problems"], 79, 47),
  mk("a347", "Shortest Path in UG with unit weights", "GeeksforGeeks", "Medium", "https://bit.ly/3UVQD4C", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 73, 48),
  mk("a348", "Shortest Path in DAG", "GeeksforGeeks", "Medium", "https://bit.ly/3Eo1mhq", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 72, 49),
  mk("a349", "Djisktra’s Algorithm", "GeeksforGeeks", "Medium", "https://bit.ly/3UsjnST", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 71, 50),
  mk("a350", "Why priority Queue is used in Djisktra’s Algorithm", "GeeksforGeeks", "Medium", "https://bit.ly/3UsjnST", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 70, 51),
  mk("a351", "Shortest path in a binary maze", "LeetCode", "Medium", "https://leetcode.com/problems/shortest-path-in-binary-matrix/", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 74, 52),
  mk("a352", "Path with minimum effort", "LeetCode", "Medium", "https://leetcode.com/problems/path-with-minimum-effort/", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 73, 53),
  mk("a353", "Cheapest flights within k stops", "LeetCode", "Medium", "https://leetcode.com/problems/cheapest-flights-within-k-stops/", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 72, 54),
  mk("a354", "Network Delay time", "LeetCode", "Medium", "https://leetcode.com/problems/network-delay-time/", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 71, 55),
  mk("a355", "Number of ways to arrive at destination", "LeetCode", "Medium", "https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 70, 56),
  mk("a356", "Minimum steps to reach end from start by performing multiplication and mod operations with array elements", "GeeksforGeeks", "Medium", "https://bit.ly/3QAEsrY", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 64, 57),
  mk("a357", "Bellman Ford Algorithm", "GeeksforGeeks", "Medium", "https://bit.ly/3C0SxKs", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 63, 58),
  mk("a358", "Floyd Warshal Algorithm", "GeeksforGeeks", "Medium", "https://bit.ly/3LwgdJP", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 62, 59),
  mk("a359", "Find the city with the smallest number of neighbors in a threshold distance", "LeetCode", "Medium", "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/", "Graphs", ["Step 15.4 Shortest Path Algorithms and Problems"], 66, 60),
  mk("a360", "Minimum Spanning Tree", "GeeksforGeeks", "Medium", "https://bit.ly/3R2Xhn1", "Graphs", ["Step 15.5 MinimumSpanningTree/Disjoint Set and Problems"], 90, 1),
  mk("a361", "Prim’s Algorithm", "GeeksforGeeks", "Medium", "https://bit.ly/3R2Xhn1", "Graphs", ["Step 15.5 MinimumSpanningTree/Disjoint Set and Problems"], 89, 2),
  mk("a362", "Disjoint Set [Union by Rank]", "GeeksforGeeks", "Medium", "https://bit.ly/3QSGvHz", "Graphs", ["Step 15.5 MinimumSpanningTree/Disjoint Set and Problems"], 88, 3),
  mk("a363", "Disjoint Set [Union by Size]", "GeeksforGeeks", "Medium", "https://bit.ly/3QSGvHz", "Graphs", ["Step 15.5 MinimumSpanningTree/Disjoint Set and Problems"], 87, 4),
  mk("a364", "Kruskal’s Algorithm", "GeeksforGeeks", "Medium", "https://bit.ly/3R2Xhn1", "Graphs", ["Step 15.5 MinimumSpanningTree/Disjoint Set and Problems"], 86, 5),
  mk("a365", "Number of operations to make network connected", "LeetCode", "Medium", "https://leetcode.com/problems/number-of-operations-to-make-network-connected/", "Graphs", ["Step 15.5 MinimumSpanningTree/Disjoint Set and Problems"], 90, 6),
  mk("a366", "Most stones removed with same rows or columns", "LeetCode", "Medium", "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/", "Graphs", ["Step 15.5 MinimumSpanningTree/Disjoint Set and Problems"], 89, 7),
  mk("a367", "Accounts merge", "LeetCode", "Medium", "https://leetcode.com/problems/accounts-merge/", "Graphs", ["Step 15.5 MinimumSpanningTree/Disjoint Set and Problems"], 88, 8),
  mk("a368", "Number of island II", "LeetCode", "Medium", "https://leetcode.com/problems/number-of-islands-ii/", "Graphs", ["Step 15.5 MinimumSpanningTree/Disjoint Set and Problems"], 87, 9),
  mk("a369", "Making a Large Island", "LeetCode", "Medium", "https://leetcode.com/problems/making-a-large-island/", "Graphs", ["Step 15.5 MinimumSpanningTree/Disjoint Set and Problems"], 86, 10),
  mk("a370", "Swim in rising water", "LeetCode", "Medium", "https://leetcode.com/problems/swim-in-rising-water/", "Graphs", ["Step 15.5 MinimumSpanningTree/Disjoint Set and Problems"], 85, 11),
  mk("a371", "Bridges in Graph", "LeetCode", "Medium", "https://leetcode.com/problems/critical-connections-in-a-network/discuss/382385/find-bridges-in-a-graph", "Graphs", ["Step 15.6 Other Algorithms"], 84, 12),
  mk("a372", "Articulation Point", "GeeksforGeeks", "Medium", "https://bit.ly/3T2LPKu", "Graphs", ["Step 15.6 Other Algorithms"], 78, 13),
  mk("a373", "Kosaraju’s Algorithm", "GeeksforGeeks", "Medium", "https://bit.ly/3TbvByL", "Graphs", ["Step 15.6 Other Algorithms"], 77, 14),
  mk("a374", "Dynamic Programming Introduction", "GeeksforGeeks", "Medium", "https://bit.ly/3UWkWrS", "Dynamic Programming", ["Step 16.1 Introduction to DP"], 76, 15),
  mk("a375", "Climbing Stars", "LeetCode", "Medium", "https://leetcode.com/problems/climbing-stairs/", "Dynamic Programming", ["Step 16.2 1D DP"], 80, 16),
  mk("a376", "Frog Jump(DP-3)", "GeeksforGeeks", "Medium", "https://bit.ly/3Xn0Kkw", "Dynamic Programming", ["Step 16.2 1D DP"], 74, 17),
  mk("a377", "Frog Jump with k distances(DP-4)", "GeeksforGeeks", "Medium", "https://bit.ly/3GyNRya", "Dynamic Programming", ["Step 16.2 1D DP"], 73, 18),
  mk("a378", "Maximum sum of non-adjacent elements (DP 5)", "GeeksforGeeks", "Medium", "https://bit.ly/3QOMRs1", "Dynamic Programming", ["Step 16.2 1D DP"], 72, 19),
  mk("a379", "House Robber (DP 6)", "GeeksforGeeks", "Medium", "https://bit.ly/3QCCpDQ", "Dynamic Programming", ["Step 16.2 1D DP"], 71, 20),
  mk("a380", "Ninja’s Training (DP 7)", "GeeksforGeeks", "Medium", "https://bit.ly/3glc9kp", "Dynamic Programming", ["Step 16.3 2D/3D DP and DP on Grids"], 70, 21),
  mk("a381", "Grid Unique Paths : DP on Grids (DP8)", "LeetCode", "Medium", "https://leetcode.com/problems/unique-paths/", "Dynamic Programming", ["Step 16.3 2D/3D DP and DP on Grids"], 74, 22),
  mk("a382", "Minimum path sum in Grid (DP 10)", "LeetCode", "Medium", "https://leetcode.com/problems/minimum-path-sum/", "Dynamic Programming", ["Step 16.3 2D/3D DP and DP on Grids"], 73, 23),
  mk("a383", "Minimum path sum in Triangular Grid (DP 11)", "LeetCode", "Medium", "https://leetcode.com/problems/triangle/", "Dynamic Programming", ["Step 16.3 2D/3D DP and DP on Grids"], 72, 24),
  mk("a384", "Minimum/Maximum Falling Path Sum (DP-12)", "LeetCode", "Medium", "https://leetcode.com/problems/minimum-falling-path-sum/", "Dynamic Programming", ["Step 16.3 2D/3D DP and DP on Grids"], 71, 25),
  mk("a385", "3-d DP : Ninja and his friends (DP-13)", "GeeksforGeeks", "Medium", "https://bit.ly/3U9k6XT", "Dynamic Programming", ["Step 16.3 2D/3D DP and DP on Grids"], 65, 26),
  mk("a386", "Subset sum equal to target (DP- 14)", "GeeksforGeeks", "Medium", "https://bit.ly/3S6ljPd", "Dynamic Programming", ["Step 16.4 DP on Subsequences"], 64, 27),
  mk("a387", "Partition Equal Subset Sum (DP- 15)", "LeetCode", "Medium", "https://leetcode.com/problems/partition-equal-subset-sum/", "Dynamic Programming", ["Step 16.4 DP on Subsequences"], 68, 28),
  mk("a388", "Partition Set Into 2 Subsets With Min Absolute Sum Diff (DP- 16)", "LeetCode", "Medium", "https://leetcode.com/problems/partition-array-into-two-arrays-to-minimize-sum-difference/", "Dynamic Programming", ["Step 16.4 DP on Subsequences"], 67, 29),
  mk("a389", "Count Subsets with Sum K (DP – 17)", "GeeksforGeeks", "Medium", "https://bit.ly/3AwVr8I", "Dynamic Programming", ["Step 16.4 DP on Subsequences"], 61, 30),
  mk("a390", "Count Partitions with Given Difference (DP – 18)", "GeeksforGeeks", "Medium", "https://bit.ly/3gkAM0s", "Dynamic Programming", ["Step 16.4 DP on Subsequences"], 90, 31),
  mk("a391", "0/1 Knapsack (DP – 19)", "GeeksforGeeks", "Medium", "https://bit.ly/3BZTjXT", "Dynamic Programming", ["Step 16.4 DP on Subsequences"], 89, 32),
  mk("a392", "Minimum Coins (DP – 20)", "LeetCode", "Medium", "https://leetcode.com/problems/coin-change/", "Dynamic Programming", ["Step 16.4 DP on Subsequences"], 93, 33),
  mk("a393", "Target Sum (DP – 21)", "LeetCode", "Medium", "https://leetcode.com/problems/target-sum/", "Dynamic Programming", ["Step 16.4 DP on Subsequences"], 92, 34),
  mk("a394", "Coin Change 2 (DP – 22)", "LeetCode", "Medium", "https://leetcode.com/problems/coin-change-2/", "Dynamic Programming", ["Step 16.4 DP on Subsequences"], 91, 35),
  mk("a395", "Unbounded Knapsack (DP – 23)", "GeeksforGeeks", "Medium", "https://bit.ly/3Cbc5fz", "Dynamic Programming", ["Step 16.4 DP on Subsequences"], 85, 36),
  mk("a396", "Rod Cutting Problem | (DP – 24)", "GeeksforGeeks", "Medium", "https://bit.ly/3R1TXZh", "Dynamic Programming", ["Step 16.4 DP on Subsequences"], 84, 37),
  mk("a397", "Longest Common Subsequence | (DP – 25)", "LeetCode", "Medium", "https://leetcode.com/problems/longest-common-subsequence/", "Dynamic Programming", ["Step 16.5 DP on Strings"], 88, 38),
  mk("a398", "Print Longest Common Subsequence | (DP – 26)", "GeeksforGeeks", "Medium", "https://bit.ly/3T1Va4U", "Dynamic Programming", ["Step 16.5 DP on Strings"], 82, 39),
  mk("a399", "Longest Common Substring | (DP – 27)", "GeeksforGeeks", "Medium", "https://bit.ly/3qYUeBK", "Dynamic Programming", ["Step 16.5 DP on Strings"], 81, 40),
  mk("a400", "Longest Palindromic Subsequence | (DP-28)", "LeetCode", "Medium", "https://leetcode.com/problems/longest-palindromic-subsequence/", "Dynamic Programming", ["Step 16.5 DP on Strings"], 85, 41),
  mk("a401", "Minimum insertions to make string palindrome | DP-29", "LeetCode", "Medium", "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/", "Dynamic Programming", ["Step 16.5 DP on Strings"], 84, 42),
  mk("a402", "Minimum Insertions/Deletions to Convert String | (DP- 30)", "LeetCode", "Medium", "https://leetcode.com/problems/delete-operation-for-two-strings/", "Dynamic Programming", ["Step 16.5 DP on Strings"], 83, 43),
  mk("a403", "Shortest Common Supersequence | (DP – 31)", "LeetCode", "Medium", "https://leetcode.com/problems/shortest-common-supersequence/", "Dynamic Programming", ["Step 16.5 DP on Strings"], 82, 44),
  mk("a404", "Distinct Subsequences| (DP-32)", "LeetCode", "Medium", "https://leetcode.com/problems/distinct-subsequences/", "Dynamic Programming", ["Step 16.5 DP on Strings"], 81, 45),
  mk("a405", "Edit Distance | (DP-33)", "LeetCode", "Medium", "https://leetcode.com/problems/edit-distance/", "Dynamic Programming", ["Step 16.5 DP on Strings"], 80, 46),
  mk("a406", "Wildcard Matching | (DP-34)", "LeetCode", "Medium", "https://leetcode.com/problems/wildcard-matching/", "Dynamic Programming", ["Step 16.5 DP on Strings"], 79, 47),
  mk("a407", "Best Time to Buy and Sell Stock |(DP-35)", "LeetCode", "Medium", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "Dynamic Programming", ["Step 16.6 DP on Stocks"], 78, 48),
  mk("a408", "Buy and Sell Stock – II|(DP-36)", "LeetCode", "Medium", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/", "Dynamic Programming", ["Step 16.6 DP on Stocks"], 77, 49),
  mk("a409", "Buy and Sell Stocks III|(DP-37)", "LeetCode", "Medium", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/description/", "Dynamic Programming", ["Step 16.6 DP on Stocks"], 76, 50),
  mk("a410", "Buy and Stock Sell IV |(DP-38)", "LeetCode", "Medium", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/", "Dynamic Programming", ["Step 16.6 DP on Stocks"], 75, 51),
  mk("a411", "Buy and Sell Stocks With Cooldown|(DP-39)", "LeetCode", "Medium", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/", "Dynamic Programming", ["Step 16.6 DP on Stocks"], 74, 52),
  mk("a412", "Longest Increasing Subsequence |(DP-41)", "LeetCode", "Medium", "https://leetcode.com/problems/longest-increasing-subsequence/", "Dynamic Programming", ["Step 16.7 DP on LIS"], 73, 53),
  mk("a413", "Printing Longest Increasing Subsequence|(DP-42)", "GeeksforGeeks", "Medium", "https://bit.ly/3XiRbmG", "Dynamic Programming", ["Step 16.7 DP on LIS"], 67, 54),
  mk("a414", "Longest Increasing Subsequence |(DP-43)", "GeeksforGeeks", "Medium", "https://bit.ly/3Pxf84L", "Dynamic Programming", ["Step 16.7 DP on LIS"], 66, 55),
  mk("a415", "Largest Divisible Subset|(DP-44)", "LeetCode", "Medium", "https://leetcode.com/problems/largest-divisible-subset/", "Dynamic Programming", ["Step 16.7 DP on LIS"], 70, 56),
  mk("a416", "Longest String Chain|(DP-45)", "LeetCode", "Medium", "https://leetcode.com/problems/longest-string-chain/", "Dynamic Programming", ["Step 16.7 DP on LIS"], 69, 57),
  mk("a417", "Longest Bitonic Subsequence |(DP-46)", "GeeksforGeeks", "Medium", "https://bit.ly/3BARIGF", "Dynamic Programming", ["Step 16.7 DP on LIS"], 63, 58),
  mk("a418", "Number of Longest Increasing Subsequences|(DP-47)", "LeetCode", "Medium", "https://leetcode.com/problems/number-of-longest-increasing-subsequence/", "Dynamic Programming", ["Step 16.7 DP on LIS"], 67, 59),
  mk("a419", "Matrix Chain Multiplication|(DP-48)", "GeeksforGeeks", "Medium", "https://bit.ly/3Cgg36D", "Dynamic Programming", ["Step 16.8 MCM DP | Partition DP"], 61, 60),
  mk("a420", "Matrix Chain Multiplication | Bottom-Up|(DP-49)", "GeeksforGeeks", "Medium", "https://bit.ly/3Cgg36D", "Dynamic Programming", ["Step 16.8 MCM DP | Partition DP"], 90, 1),
  mk("a421", "Minimum Cost to Cut the Stick|(DP-50)", "LeetCode", "Medium", "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/", "Dynamic Programming", ["Step 16.8 MCM DP | Partition DP"], 94, 2),
  mk("a422", "Burst Balloons|(DP-51)", "LeetCode", "Medium", "https://leetcode.com/problems/burst-balloons/", "Dynamic Programming", ["Step 16.8 MCM DP | Partition DP"], 93, 3),
  mk("a423", "Evaluate Boolean Expression to True|(DP-52)", "LeetCode", "Medium", "https://leetcode.com/problems/parsing-a-boolean-expression/", "Dynamic Programming", ["Step 16.8 MCM DP | Partition DP"], 92, 4),
  mk("a424", "Palindrome Partitioning – II|(DP-53)", "LeetCode", "Medium", "https://leetcode.com/problems/palindrome-partitioning-ii/", "Dynamic Programming", ["Step 16.8 MCM DP | Partition DP"], 91, 5),
  mk("a425", "Partition Array for Maximum Sum|(DP-54)", "LeetCode", "Medium", "https://leetcode.com/problems/partition-array-for-maximum-sum/", "Dynamic Programming", ["Step 16.8 MCM DP | Partition DP"], 90, 6),
  mk("a426", "Maximum Rectangle Area with all 1’s|(DP-55)", "LeetCode", "Medium", "https://leetcode.com/problems/maximal-rectangle/", "Dynamic Programming", ["Step 16.9 DP on Squares"], 89, 7),
  mk("a427", "Count Square Submatrices with All Ones|(DP-56)", "LeetCode", "Medium", "https://leetcode.com/problems/count-square-submatrices-with-all-ones/", "Dynamic Programming", ["Step 16.9 DP on Squares"], 88, 8),
  mk("a428", "Implement TRIE | INSERT | SEARCH | STARTSWITH", "LeetCode", "Easy", "https://leetcode.com/problems/implement-trie-prefix-tree/", "Tries", ["Step 17.1 Theory"], 87, 9),
  mk("a429", "Implement Trie – 2 (Prefix Tree)", "GeeksforGeeks", "Easy", "https://bit.ly/3SUAiwJ", "Tries", ["Step 17.2 Problems"], 81, 10),
  mk("a430", "Longest String with All Prefixes", "GeeksforGeeks", "Easy", "https://bit.ly/3Qx5AYB", "Tries", ["Step 17.2 Problems"], 80, 11),
  mk("a431", "Number of Distinct Substrings in a String", "GeeksforGeeks", "Easy", "https://bit.ly/3UoqdsB", "Tries", ["Step 17.2 Problems"], 79, 12),
  mk("a432", "Bit PreRequisites for TRIE Problems", "GeeksforGeeks", "Easy", "https://bit.ly/3Vw4XB1", "Tries", ["Step 17.2 Problems"], 78, 13),
  mk("a433", "Maximum XOR of two numbers in an array", "LeetCode", "Easy", "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/", "Tries", ["Step 17.2 Problems"], 82, 14),
  mk("a434", "Maximum XOR With an Element From Array", "LeetCode", "Easy", "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/", "Tries", ["Step 17.2 Problems"], 81, 15),
  mk("a435", "Minimum number of bracket reversals needed to make an expression balanced", "LeetCode", "Hard", "https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/", "Strings", ["Step 18.1 Hard Problems"], 80, 16),
  mk("a436", "Count and say", "LeetCode", "Hard", "https://leetcode.com/problems/count-and-say/", "Strings", ["Step 18.1 Hard Problems"], 79, 17),
  mk("a437", "Hashing In Strings | Theory", "GeeksforGeeks", "Hard", "https://bit.ly/3glak75", "Strings", ["Step 18.1 Hard Problems"], 73, 18),
  mk("a438", "Rabin Karp", "GeeksforGeeks", "Hard", "https://bit.ly/3SkQqGw", "Strings", ["Step 18.1 Hard Problems"], 72, 19),
  mk("a439", "Z-Function", "GeeksforGeeks", "Hard", "https://bit.ly/3dBLAGb", "Strings", ["Step 18.1 Hard Problems"], 71, 20),
  mk("a440", "KMP algo / LPS(pi) array", "GeeksforGeeks", "Hard", "https://bit.ly/3fdJzQM", "Strings", ["Step 18.1 Hard Problems"], 70, 21),
  mk("a441", "Shortest Palindrome", "LeetCode", "Hard", "https://leetcode.com/problems/shortest-palindrome/", "Strings", ["Step 18.1 Hard Problems"], 74, 22),
  mk("a442", "Longest happy prefix", "LeetCode", "Hard", "https://leetcode.com/problems/longest-happy-prefix/", "Strings", ["Step 18.1 Hard Problems"], 73, 23),
  mk("a443", "Count palindromic subsequence in given string", "GeeksforGeeks", "Hard", "https://bit.ly/3xHw6Hs", "Strings", ["Step 18.1 Hard Problems"], 67, 24),
  mk("a445", "Print Prime Factors of a Number", "GeeksforGeeks", "Medium", "https://bit.ly/3C165p8", "Bit Manipulation", ["Step 8.3 Advanced Maths"], 65, 26),
  mk("a446", "All Divisors of a Number", "GeeksforGeeks", "Medium", "https://practice.geeksforgeeks.org/problems/all-divisors-of-a-number/1?utm_source=youtube&amp;utm_medium=collab_striver_ytdescription&amp;utm_campaign=all-divisors-of-a-number", "Bit Manipulation", ["Step 8.3 Advanced Maths"], 64, 27),
  mk("a447", "Sieve of Eratosthenes", "LeetCode", "Medium", "https://leetcode.com/problems/count-primes/", "Bit Manipulation", ["Step 8.3 Advanced Maths"], 68, 28),
  mk("a448", "Power(n, x)", "LeetCode", "Medium", "https://leetcode.com/problems/powx-n/", "Bit Manipulation", ["Step 8.3 Advanced Maths"], 67, 29),
  mk("a449", "Find Prime Factorisation of a Number using Sieve", "GeeksforGeeks", "Medium", "https://bit.ly/3SPGzbK", "Bit Manipulation", ["Step 8.3 Advanced Maths"], 61, 30),
];

export const PLATFORM_META: Record<
  Platform,
  { color: string; initials: string; url: string; logo: string }
> = {
  LeetCode: {
    color: "from-amber-500 to-orange-600",
    initials: "LC",
    url: "https://leetcode.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/19/LeetCode_logo_black.png",
  },
  GeeksforGeeks: {
    color: "from-emerald-500 to-green-700",
    initials: "GFG",
    url: "https://geeksforgeeks.org",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/43/GeeksforGeeks.svg",
  },
  Codeforces: {
    color: "from-sky-500 to-blue-700",
    initials: "CF",
    url: "https://codeforces.com",
    logo: "https://codeforces.org/s/0/favicon-96x96.png",
  },
  CodeChef: {
    color: "from-amber-700 to-stone-800",
    initials: "CC",
    url: "https://codechef.com",
    logo: "https://cdn.codechef.com/images/cc-logo.png",
  },
};
