/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as VisualizersRouteImport } from './routes/visualizers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualizersSlugRouteImport } from './routes/visualizers.$slug'
import { Route as ApiTutorRouteImport } from './routes/api/tutor'
import { Route as ApiInterviewRouteImport } from './routes/api/interview'
import { Route as ApiHintRouteImport } from './routes/api/hint'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizersRoute = VisualizersRouteImport.update({
  id: '/visualizers',
  path: '/visualizers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizersSlugRoute = VisualizersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VisualizersRoute,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewRoute = ApiInterviewRouteImport.update({
  id: '/api/interview',
  path: '/api/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHintRoute = ApiHintRouteImport.update({
  id: '/api/hint',
  path: '/api/hint',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/visualizers': typeof VisualizersRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/api/hint': typeof ApiHintRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/tutor': typeof ApiTutorRoute
  '/visualizers/$slug': typeof VisualizersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/visualizers': typeof VisualizersRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/api/hint': typeof ApiHintRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/tutor': typeof ApiTutorRoute
  '/visualizers/$slug': typeof VisualizersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/visualizers': typeof VisualizersRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/api/hint': typeof ApiHintRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/tutor': typeof ApiTutorRoute
  '/visualizers/$slug': typeof VisualizersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/practice'
    | '/profile'
    | '/visualizers'
    | '/workspace'
    | '/api/hint'
    | '/api/interview'
    | '/api/tutor'
    | '/visualizers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/practice'
    | '/profile'
    | '/visualizers'
    | '/workspace'
    | '/api/hint'
    | '/api/interview'
    | '/api/tutor'
    | '/visualizers/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/practice'
    | '/profile'
    | '/visualizers'
    | '/workspace'
    | '/api/hint'
    | '/api/interview'
    | '/api/tutor'
    | '/visualizers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  InterviewRoute: typeof InterviewRoute
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
  VisualizersRoute: typeof VisualizersRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRoute
  ApiHintRoute: typeof ApiHintRoute
  ApiInterviewRoute: typeof ApiInterviewRoute
  ApiTutorRoute: typeof ApiTutorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizers': {
      id: '/visualizers'
      path: '/visualizers'
      fullPath: '/visualizers'
      preLoaderRoute: typeof VisualizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizers/$slug': {
      id: '/visualizers/$slug'
      path: '/$slug'
      fullPath: '/visualizers/$slug'
      preLoaderRoute: typeof VisualizersSlugRouteImport
      parentRoute: typeof VisualizersRoute
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview': {
      id: '/api/interview'
      path: '/api/interview'
      fullPath: '/api/interview'
      preLoaderRoute: typeof ApiInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hint': {
      id: '/api/hint'
      path: '/api/hint'
      fullPath: '/api/hint'
      preLoaderRoute: typeof ApiHintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VisualizersRouteChildren {
  VisualizersSlugRoute: typeof VisualizersSlugRoute
}

const VisualizersRouteChildren: VisualizersRouteChildren = {
  VisualizersSlugRoute: VisualizersSlugRoute,
}

const VisualizersRouteWithChildren = VisualizersRoute._addFileChildren(
  VisualizersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  InterviewRoute: InterviewRoute,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
  VisualizersRoute: VisualizersRouteWithChildren,
  WorkspaceRoute: WorkspaceRoute,
  ApiHintRoute: ApiHintRoute,
  ApiInterviewRoute: ApiInterviewRoute,
  ApiTutorRoute: ApiTutorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
